admin:
  address:
    socket_address: {address: 0.0.0.0, port_value: 9901}

static_resources:
  listeners:
  - name: listener1
    address:
      socket_address: {address: 0.0.0.0, port_value: 51051}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          local_reply_config:
             mappers:
             - filter:
                  status_code_filter:
                    comparison:
                      op: EQ
                      value:
                        default_value: 400
                        runtime_key: key_b
               status_code: 400
               body_format_override:
                  json_format:
                    status: 'ERROR'
                    message: 'Invalid input value!'
                  content_type: "application/json"
          stat_prefix: grpc_json
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: "POST,  OPTIONS"
                allow_headers: "authorization, keep-alive, user-agent, cache-control, content-type, content-transfer-encoding, x-accept-content-transfer-encoding, x-accept-response-streaming, x-user-agent, x-grpc-web, referer,,language"
                expose_headers: "grpc-status, grpc-message, x-envoy-upstream-service-time"
              domains: ["*"]
              routes:
                - match:
                    prefix: "/"
                    headers:
                      - name: ":method"
                        exact_match: OPTIONS
                  direct_response:
                    status: 200
                - match:
                    prefix: "/v1/recognize"
                  direct_response:
                    status: 406
                    body:
                      inline_string: "Given Content-type is not allowed"
                - match:
                    prefix: "/v1/punctuate"
                  direct_response:
                    status: 406
                    body:
                      inline_string: "Given Content-type is not allowed"
                - match:
                    prefix: "/"
                  direct_response:
                    status: 404
                    body:
                      inline_string: "Not Found"
          http_filters:
          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "/config/api_descriptor.pb"
              services: ["ekstep.speech_recognition.SpeechRecognizer"]
              match_incoming_request_route: true
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: true
          - name: envoy.filters.http.router

  clusters: []
