base_name: asr-model-v2
config:
  - languages:
      - en
      - hi
      - bn
      - pa
    cpu:
      count: 4
  - languages:
      - mr
      - mai
      - te
      - ne
    cpu:
      count: 4
  - languages:
      - gu
      - kn
      - ta
      - doi
      - raj
    cpu:
      count: 2
  - languages:
      - ur
      - ml
      - or
      - sa
      - bo
    cpu:
      count: 4

  
