base_name: asr-model-v2
config:
  - languages:
      - en
      - pa
      - raj
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - mr
      - mai
      - te
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - gu
      - kn
      - ta
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - ur
      - ml
      - hi
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - or
      - sa
      - bho
      - as
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - bn
      - ne
      - doi
    gpu:
      count: 0
      accelerator: ''
