base_name: asr-model-v2
config:
  - languages:
      - en
      - bn
      - pa
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - mr
      - mai
      - te
      - ne
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - gu
      - kn
      - ta
      - doi
      - raj
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - ur
      - ml
      - hi
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - or
      - sa
      - bho
    gpu:
      count: 0
      accelerator: ''
