base_name: asr-model-v2
config:
  - languages:
      - en
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "2"
    replicaCount: 3
    nodeName: "scn32-100g"
  - languages:
      - ne
      - doi
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "1"
  - languages:
      - as
      - mr
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "1"
  - languages:
      - bn
      - gu
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "1"
  - languages:
      - kn
      - ml
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "1"
  - languages:
      - pa
      - te
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "2"
  - languages:
      - ur
      - ta
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "2"
  - languages:
      - hi
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "2"
    replicaCount: 3
  - languages:
      - or
      - sa
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "2"
  - languages:
      - bho
      - mai
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
      CUDA_VISIBLE_DEVICES: "1"