base_name: asr-model-v2
config:
  - languages:
      - en
      - hi
      - bn
      - as
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
  - languages:
      - mr
      - mai
      - te
      - ne
      - doi
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
  - languages:
      - gu
      - kn
      - ta
      - pa
      - raj
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
  - languages:
      - ur
      - ml
      - or
      - sa
      - bo
    gpu:
      count: 1
      accelerator: 'Tesla-T4'