base_name: asr-model-v2
config:
  - languages:
      - en
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
    replicaCount: 2
  - languages:
      - ne
      - doi
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
  - languages:
      - as
      - mr
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
  - languages:
      - mai
      - gu
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
  - languages:
      - kn
      - ml
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
  - languages:
      - pa
      - te
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
  - languages:
      - ur
      - ta
    gpu:
      count: 0
      accelerator: 'Tesla-T4'
  - languages:
      - hi
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
  - languages:
      - or
      - sa
    gpu:
      count: 0
      accelerator: 'nvidia-A100'
  - languages:
      - bho
      - bn
    gpu:
      count: 0
      accelerator: 'nvidia-A100'