base_name: asr-model-v2
config:
  - languages:
      - en
      - hi
      - bn
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
  - languages:
      - mr
      - mai
      - te
      - ne
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
  - languages:
      - gu
      - kn
      - ta
    gpu:
      count: 1
      accelerator: 'Tesla-T4'
  - languages:
      - ur
      - ml
      - or
      - sa
    gpu:
      count: 1
      accelerator: 'Tesla-T4'