base_name: asr-model-v2
config:
  - languages:
      - en
      - ne
      - doi
      - as
      - mr
    gpu:
      count: 0
      accelerator: 'Tesla-T4'
  - languages:
      - gu
      - kn
      - ta
      - pa
      - raj
      - te
    gpu:
      count: 0
      accelerator: 'Tesla-T4'
  - languages:
      - ur
      - hi
      - ml
      - or
      - bho
    gpu:
      count: 0
      accelerator: 'Tesla-T4'
  - languages:
      - bn
      - sa
      - mai
    gpu:
      count: 0
      accelerator: 'Tesla-T4'
