base_name: asr-model-v2
config:
  - languages:
      - en
      - ne
      - doi
      - as
      - mr
      - mai
    gpu:
      count: 1
      accelerator: ''
  - languages:
      - gu
      - kn
      - ta
      - pa
      - raj
      - te
      - bn
    gpu:
      count: 1
      accelerator: ''
  - languages:
      - ur
      - hi
      - ml
      - or
      - sa
      - bo
    gpu:
      count: 1
      accelerator: ''
