base_name: asr-model-v2
config:
  - languages:
      - en
      - ne
      - doi
      - as
      - mr
      - mai
      - gu
      - kn
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - ur
      - hi
      - ml
      - or
      - sa
      - bn
      - bho
      - pa
      - te
      - ta
    gpu:
      count: 0
      accelerator: ''
