base_name: asr-model-v2
config:
  - languages:
      - en
      - hi
      - bn
  - languages:
      - mr
      - mai
      - te
  - languages:
      - ne
      - pa
      - sa
      - as
  - languages:
      - gu
      - kn
      - ta
  - languages:
      - doi
      - raj
      - bo
  - languages:
      - ur
      - ml
      - or
