base_name: asr-model-v2
config:
  - languages:
      - ne
      - doi
      - as
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - en
      - kn
      - ml
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - mai
      - gu
      - pa
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - hi
      - ta
      - or
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - bho
      - bn
      - sa
    gpu:
      count: 0
      accelerator: ''
  - languages:
      - ur
      - te
      - mr
    gpu:
      count: 0
      accelerator: ''
