apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
data:
  envoy.yaml: |- {{ .Files.Get "config.yaml" | nindent 4 }}
  api_descriptor.pb: |- {{ .Files.Get "api_descriptor.pb" | nindent 4 }}
