apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asr-model-v2.fullname" . }}
  labels:
    {{- include "asr-model-v2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "asr-model-v2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "asr-model-v2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "asr-model-v2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        # - name: {{ .Values.volumes.name }}
        #   hostPath:
        #     path: {{ .Values.volumes.path }}
        #     type: {{ .Values.volumes.type }}
#          persistentVolumeClaim:
#            claimName: {{ .Values.volumes.claimName }}
#            readOnly: {{ .Values.volumes.readOnly }}
        - gcePersistentDisk:
           pdName: {{ .Values.volumes.pdName }}
           fsType: {{ .Values.volumes.fsType }}
           readOnly: {{ .Values.volumes.readOnly }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: languages
              value: {{ .Values.env.languages | squote }}
            - name: gpu
              value: {{ .Values.env.gpu | quote }}

          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: {{ .Values.volumes.mountPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
