apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api-v2
  namespace: test
  labels:
    app: model-api-v2
    language: all
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-api-v2
      language: all
  template:
    metadata:
      labels:
        app: model-api-v2
        language: all
    spec:
      volumes:
        - name: modelsv2
          gcePersistentDisk:
            pdName: modelsv2
            fsType: ext4
            readOnly: true
      containers:
        - name: speech-recognition-model-api
          image: 'gcr.io/ekstepspeechrecognition/speech_recognition_model_api:2.0.0'
          env: 
          - name: languages
            value: '["hi"]'
          ports:
            - containerPort: 50051
              protocol: TCP
#          resources:
#            limits:
#                cpu: '500m'
#                memory: "2Gi"
          volumeMounts:
            - name: modelsv2
              mountPath: /opt/speech_recognition_open_api/deployed_models/
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

