apiVersion: v1
kind: Service
metadata:
  name: model-api-v2-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: model-api-v2
    language: all
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

